LANGCHAIN_API_KEY=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
OPENAI_API_KEY=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
LANGCHAIN_PROJECT=Tutorial
