LANGCHAIN_API_KEY=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
OPENAI_API_KEY=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
LANGCHAIN_PROJECT=Tutorial
