LANGCHAIN_API_KEY=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
OPENAI_API_KEY=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
LANGCHAIN_PROJECT=Tutorial
